### ISSUE TITLE
What manual edits are required after generation?

### ISSUE THREAD

**Issue by joshgav** [MSOpenTech/vipr-t4templatewriter#4]
Please list all edits to autogenerated code currently required, such as multipart fetchers for OneNote, edits for OData functions and actions, namespace/package name overrides, etc. Thanks!

**Comment by anihojnadel** [comment]
Fist, configure T4TemplateWriter, then follow the steps for the SDK you want to regenerate. Finally, run the project and find the generated code in debug\output folder.

To configure T4TemplateWriter:
- Open Vipr.T4TemplateWriter project's properties and use the following debug settings:
  - Start Action -> Start External Program (...\vipr-t4templatewriter\src\T4TemplateWriter\bin\debug\Vipr.exe)
  - Command line Arguments: 
    {metadata path}\metadata.xml --writer='Vipr.T4TemplateWriter'

To configure SDK (Android):
- Exchange
  - In metadata, rename entityContainer to Outlook
  - In TemplateWriterSettings.json, set NamespaceOverride to "com.microsoft.services.outlook"
- Files
  - In metadata, rename entityContainer to Files
  - In TemplateWriterSettings.json:
    Set NamespaceOverride to "com.microsoft.services.files"
    Specify PrimaryNamespace (First use "Microsoft.FileServices", then "Microsoft.CoreServices")
    Regenerate the SDK twice, one with each namespace and merge the results into same folder. Use Client generated for FileServices namespace
  - Once regenerated, update to use Http.GET the following function:
    - FileOperations -> content
- Discovery
  - In metadata, rename entityContainer to Discovery
  - In TemplateWriterSettings.json, set NamespaceOverride to "com.microsoft.services.discovery"
- OneNote
  - In metadata, rename entityContainer to OneNoteApi
  - In TemplateWriterSettings.json, set NamespaceOverride to "com.microsoft.services.onenote"
  - Remove <annotations> tag from metadata
  - Once generated, change return type to MultipartCollectionFetcher in the GetPages method within NotesFetcher and SectionFetcher
  - Then, update to use Http.GET the following function:
    - SiteCollectionCollectionOperations -> fromUrl
- Graph
  - In metadata, rename entityContainer to Graph
  - In TemplateWriterSettings.json, set NamespaceOverride to "com.microsoft.services.graph"
  - Once regenerated, update to use Http.GET the following function:
    - ItemOperations -> content
- Directory
  - Metadata is broken

To configure SDK (Objective C):
- Exchange
  - In metadata, rename entityContainer to Outlook
- Files
  - In metadata, rename entityContainer to SharePoint
  - In TemplateWriterSettings.json:
    - Specify PrimaryNamespace (First use "Microsoft.FileServices", then "Microsoft.CoreServices")
    - Regenerate the SDK twice, one with each namespace and merge the results into same folder. Use Client generated for FileServices namespace
- Discovery
  - In metadata, rename entityContainer to Discovery
- OneNote
  - In metadata, rename entityContainer to OneNote
  - Remove <annotations> tag from metadata
  - Once generated, change return type to MSMultipartCollectionFetcher in the GetPages method within NotesFetcher and SectionFetcher
- Graph
  - In metadata, rename entityContainer to Graph
- Directory
  - Metadata is broken
